#ifndef LOUVAIN_H
#define LOUVAIN_H

#include "Graph.h"
#include <vector>
#include <unordered_map>
#include <stack> // Required for Tree Splitting re-attachment

/**
 * @class Louvain
 * @brief Implements the Louvain algorithm with optional "Fast Louvain" improvements.
 *
 * Improvements based on "An Improved Louvain Algorithm for Community Detection":
 * 1. Splitting Local Tree Structures (Pruning leaves before iteration).
 * 2. Dynamic Iterative Optimization (Relaxed convergence threshold).
 */
class Louvain {
public:
    /**
     * @brief Constructor
     * @param g The graph.
     * @param fast_mode If true, enables Tree Splitting and Dynamic Iteration.
     */
    Louvain(const Graph& g, bool fast_mode = false);

    /**
     * @brief Runs Phase 1 (Modularity Optimization).
     * In fast_mode, this includes pruning trees and using a relaxed stopping condition.
     */
    bool run_phase_one();

    /**
     * @brief Runs Phase 2 (Community Aggregation).
     */
    Graph run_phase_two();

    /**
     * @brief Returns the current community assignment for all nodes.
     */
    std::unordered_map<int, int> get_community_assignments() const;

    /**
     * @brief Returns the mapping from old community IDs to new node IDs (from Phase 2).
     */
    const std::unordered_map<int, int>& get_comm_remap() const {
        return m_comm_to_new_node;
    }

    // --- Benchmarking Helpers ---
    long long get_step_count() const { return calculation_steps; }
    void reset_step_count() { calculation_steps = 0; }

private:
    double calculate_delta_modularity(int node, int target_community);
    void move_node(int node, int target_community);

    // --- Improvement 1: Tree Splitting Methods ---
    /**
     * @brief Identifies and removes local tree structures (leaves) before iteration.
     * Only active when fast_mode is true.
     */
    void prune_local_trees();

    /**
     * @brief Re-attaches pruned nodes to the community of their parent.
     * Only active when fast_mode is true.
     */
    void reattach_trees();

    // --- Graph & State Data ---
    const Graph& graph;
    double m2;
    int n;
    bool use_fast_mode;           // Toggle for improvements
    long long calculation_steps;  // Counter for benchmarking

    // Mappings
    std::unordered_map<int, int> node_to_internal_id;
    std::vector<int> internal_id_to_node;
    
    // Map generated by run_phase_two {old_comm_id -> new_node_id}
    std::unordered_map<int, int> m_comm_to_new_node;

    // Algorithm State
    std::vector<int> community_of_node;
    std::vector<double> community_total_degree;
    std::vector<double> community_internal_weight;

    // --- Fast Louvain Specific Structures ---
    // Mask to skip pruned nodes during iteration
    std::vector<bool> is_active; 

    // Stack stores {child, parent} pairs for correct re-attachment order (LIFO)
    std::stack<std::pair<int, int>> pruned_nodes_stack; 
};

#endif // LOUVAIN_H